Bookstore: initialize project with components
leonardoeng13/Bookstore pull request #1
Opened 2021-10-05 19:45 UTC by leonardoeng13

### In this project milestone I accomplished the following :
- [ ] Set-up react app using react documentation.
- [ ] Add React Redux
- [ ] Structure your application files using a "feature folder"
- [ ] Add React Router and set two s and s for the app's navigation (Books and Categories)
   - Books - the default view
      - Displayed the list of books (empty at this point but it should be ready for the data) with the Remove button (no functionality yet)
      - Had a form for adding a book (no functionality yet)
  - Categories
      -  Displayed "Under construction" text only.
- [ ] Follow Gitflow requirements.
- [ ] Set up my local environment to fix all linters errors.
- [ ] Deploy the app with Netlify

_**Thank you in advance for your feedback**_

2021-10-05 21:01 UTC, GzimAsani requested changes
# Hi @leonardoeng13   
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight:
- Good use of gitflow :+1: 

## Required Changes ♻️
- [ ] _Check the comments under the review for more information._


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-05 21:01 UTC, GzimAsani commented on package.json
> +  "dependencies": {
`react-router-dom` should be present in package.json
`react-router-dom` will be needed to make the routes

2021-10-05 21:01 UTC, GzimAsani commented on src/index.js
> +// import reportWebVitals from './reportWebVitals';
- [ ] Remove the commented code

2021-10-05 21:01 UTC, GzimAsani commented on README.md
> + </br> -->
- [ ] Remove commented code

2021-10-05 21:01 UTC, GzimAsani commented on README.md
> +# Getting Started with Create React App
- [ ] Be more specific here. Explain how to clone the project

2021-10-05 21:06 UTC, leonardoeng13 commented on README.md
> +# Getting Started with Create React App
Do you know this part of the project it's just the components and don't have anything functional? Do you know this?

2021-10-05 21:08 UTC, leonardoeng13 commented on README.md
> +# Getting Started with Create React App
And the information is already there. Do you how to check the right branch?

2021-10-06 10:43 UTC, bellom commented on package.json
> +  "dependencies": {
According to the project requirements, you're supposed to add `react-router-dom`
Screenshot from the requirement page:
![image](https://user-images.githubusercontent.com/31897434/136188232-73d7fe93-05fb-4b43-a92e-204404b39e8e.png)

2021-10-06 10:48 UTC, bellom commented
Hello 👋,

This is an additional review as a result of the second opinion request.

@leonardoeng13 Keep in mind that there is a review guideline the reviewer followed which is also aligned with the project requirements, according to the [project requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/bookstore/project_init_project_wth_comps.md#project-requirements) (bullet 4) you're supposed to add `react-router-dom`.
And also, as you can see above, the reviewer drop some inline comments on `feature/component` branch, I don't understand the question you asked the reviewer, from what I can see the reviewer checked the right branch, and you're missing the setup setting in your README file.

Example of a good setup setting:
```
- git clone "your repo"
- cd into the folder
- git checkout "branch-name"
- run "npm i"
- run "npm start"
```
@leonardoeng13 Please let's be more professional in our comments next time, code reviewers are doing their best to help and to correct students politely. 👍 

@GzimAsani, In your next review, please it would be nice to show the students they are wrong than telling them they are wrong, explain the reason why you're asking for changes, and also, you can always write an inline comment with screenshots, check my inline comment above.

@leonardoeng13 Kindly make all necessary changes and ask for a re-review.

Keep rocking 🚀!

2021-10-06 18:05 UTC, GzimAsani requested changes
# Hi @leonardoeng13   
Good job so far!
Thank you for implementing the requirements but unfortunately, there are still some issues that you still need to work on to go to the next project but you are almost there!

## To highlight:
- Good use of gitflow :+1: 

## Required Changes ♻️
- [ ] _Check the comments under the review for more information._


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-06 18:05 UTC, GzimAsani commented on README.md
> +- git clone "your repo"
- [x] Add your repo inside parentheses**("")** in your case it should be "https://github.com/leonardoeng13/Bookstore.git". Keep in mind that your Readme may be red by people that are not that familiar with programming and you should try to make the steps in your readme file as simple as possible

2021-10-06 18:05 UTC, GzimAsani commented on README.md
> +- git checkout "branch-name"
- [x] Enter your branch name here

2021-10-06 18:05 UTC, GzimAsani commented on README.md
> + </br> -->
- [ ] Please remove the commented code, it is not a good practice

2021-10-06 18:16 UTC, GzimAsani approved these changes
# STATUS: APPROVED :100:         

## Thank you for implementing all the project requirements, you've done a great job :trophy:  . There is nothing else to say other than... it's time to merge it :champagne:  :tada: Congratulations

Cheers and Happy coding! :clap:  :computer:  :wine_glass: 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-06 18:16 UTC, merged